config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  resources :shopping_lists do
    post "send_email_now", on: :member
  end
  resources :products
  resources :shopping_list_emails, only: %i(new create edit update destroy)
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
    end
  end
end

app/models/shopping_list.rb
# frozen_string_literal: true

class ShoppingList < ApplicationRecord
  attr_accessor :send_email

  has_many :shopping_list_products, dependent: :destroy
  has_many :products, through: :shopping_list_products
  has_one :shopping_list_email, dependent: :destroy
  accepts_nested_attributes_for :shopping_list_products, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :shopping_list_email, reject_if: :all_blank, allow_destroy: true
  enum :status, { pending: 0, done: 1 }
end

app/controllers/shopping_lists_controller.rb
# frozen_string_literal: true

class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: %i(show edit update destroy)

  def index
    @shopping_lists = repository.all
  end

  def show
    respond_to do |format|
      format.xlsx { xlsx_format }
      format.html
      format.csv { csv_format }
      format.pdf { pdf_format }
    end
  end

  def new
    @shopping_list = repository.new_entity
    @all_products = products_repository.all
    build_shopping_list_product
    build_shopping_list_email
    @file_formats = available_file_formats
    @statuses = available_statuses
  end

  def edit
    @all_products = products_repository.all
    build_shopping_list_product
    build_shopping_list_email
    @file_formats = available_file_formats
    @statuses = available_statuses
  end

  def create
    check_email_selection
    @shopping_list = repository.new_entity(attrs: shopping_list_params)

    if repository.save(@shopping_list)
      redirect_to shopping_list_url(@shopping_list), notice: "Shopping list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    check_email_selection
    @shopping_list.attributes = shopping_list_params

    if repository.save(@shopping_list)
      redirect_to shopping_list_url(@shopping_list), notice: "Shopping list was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    repository.delete(@shopping_list)

    redirect_to shopping_lists_url, notice: "Shopping list was successfully destroyed."
  end

  def send_email_now
    @shopping_list = repository.find(id: params[:id])
    ShoppingListMailer.with(shopping_list: @shopping_list).shopping_list_email.deliver_now
    render :show, notice: "Shopping list was send."
  end

  private

  def repository
    @repository ||= ShoppingLists::Repository.new
  end

  def products_repository
    @products_repository ||= Products::Repository.new
  end

  def set_shopping_list
    @shopping_list = repository.find(id: params[:id])
  end

  def shopping_list_params
    params
      .require(:shopping_list)
      .permit(
        :name,
        :shopping_day,
        :status,
        :send_email,
        shopping_list_products_attributes: %i(
          id
          shopping_list_id
          product_id
          quantity
          _destroy
        ),
        shopping_list_email_attributes: %i(
          id
          shopping_list_id
          send_date
          file_format
          recipient
          was_send
          _destroy
        ),
      )
  end

  def check_email_selection
    return unless params.dig(:shopping_list, :send_email) == "0"

    params[:shopping_list].delete :shopping_list_email_attributes
  end

  def build_shopping_list_product
    @shopping_list_product = @shopping_list.shopping_list_products.build
  end

  def build_shopping_list_email
    @shopping_list_email = @shopping_list.build_shopping_list_email
  end

  def file_name
    "#{@shopping_list.name}_#{@shopping_list.shopping_day}"
  end

  def xlsx_format
    response.headers["Content-Disposition"] = "attachment; filename=#{file_name}.xlsx"
  end

  def csv_format
    response.headers["Content-Type"] = "text/csv"
    response.headers["Content-Disposition"] = "attachment; filename=#{file_name}.csv"
  end

  def pdf_format
    pdf = ShoppingLists::UseCases::CreatePdf.new(@shopping_list)
    send_data pdf.render, filename: file_name.to_s,
                          type: "application/pdf",
                          disposition: "inline"
  end

  def available_file_formats
    ShoppingListEmail.file_formats.keys
  end

  def available_statuses
    repository.all.statuses.keys
  end
end

app/helpers/shopping_lists_helper.rb
# frozen_string_literal: true

module ShoppingListsHelper
end

app/views/shopping_lists/_form.html.haml
.form-container.bg-light.mx-5
  = form_with model: @shopping_list, data: { controller: "nested-form", nested_form_wrapper_selector_value: ".nested-form-wrapper" } do |f|
    .row.m-2.py-2
      .col-6.col-sm-2.d-flex.flex-column
        .pe-2.py-2.text-muted.fw-light.text-start= f.label :status, "Status:"
        #input-shopping-list-status= f.select :status, options_for_select(@statuses, f.object.status), {}, class: "form-select"
      .col-12.col-sm-6.d-flex.flex-column
        .pe-2.py-2.text-muted.fw-light.text-start= f.label :name, "Name:"
        #input-shopping-list-name= f.text_field :name, class: "form-control", placeholder: :name
      .col-12.col-sm-4.d-flex.flex-column
        .pe-2.py-2.text-muted.fw-light.text-start= f.label :shopping_day, "Shopping Day:"
        #input-shopping-list-date= f.date_field :shopping_day, class: "form-control", placeholder: :shopping_day
    -# adding products section
    .row.m-2.py-2
      .col-8.overflow-auto
        #sl-products-list-container.position-relative
          .pe-2.text-muted.fw-light Products:
          %template{"data-nested-form-target" => "template"}
            = f.fields_for :shopping_list_products, @shopping_list_product, child_index: "NEW_RECORD" do |builder|
              = render "shopping_list_product_fields", f: builder

          = f.fields_for :shopping_list_products do |builder|
            = render "shopping_list_product_fields", f: builder

          %div{"data-nested-form-target" => "target"}
          %button.btn.btn-outline-dark.me-2{"data-action" => "nested-form#add", type: "button"} Add Product
      -# setting up email section
      .col-4.py-4
        #sl-email-container.position-relative
          .form-check
            = f.check_box :send_email, class: "form-check-input"
            .pe-2.text-muted.fw-light= f.label :send_email, "Send me the list by email", class: "form-check-label"
          - if :send_email
            = f.fields_for :shopping_list_email, @shopping_list_email do |email|
              .d-flex.flex-column
                .pe-2.py-2.text-muted.fw-light.text-start= email.label :send_date, "When:"
                #input-shopping-list-status= email.date_field :send_date, class: "form-select", placeholder: Date.today
              .d-flex.flex-column
                .pe-2.py-2.text-muted.fw-light.text-start= email.label :file_format, "Format:"
                #input-shopping-list-date= email.select :file_format, options_for_select(@file_formats, email.object.file_format), {}, class: "form-control"
              .d-flex.flex-column
                .pe-2.py-2.text-muted.fw-light.text-start= email.label :recipient, "Email adress:"
                #input-shopping-list-name= email.email_field :recipient, class: "form-control"
              = email.hidden_field :was_send, value: false

    -# subbmition
    .p-4
      = link_to "Show", @shopping_list, class: "btn btn-outline-dark" if @shopping_list.id
      = f.submit @shopping_list.id ? "Save" : "Create", class: "btn btn-dark me-2", type: "submit"

app/views/shopping_lists/_shopping_list_product_fields.html.haml
.nested-form-wrapper{"data-new-record" => f.object.new_record?}
  .d-flex
    = f.select :product_id, options_from_collection_for_select(@all_products, :id, :name, f.object.product_id), {}, {class: "form-select"}
    .flex-grow-1= f.number_field :quantity, in: 1..1000, step: 1, class: "form-control"
    %button.btn.btn-sm.btn-outline-danger{"data-action" => "nested-form#remove", :type => "button"} Remove

    = f.hidden_field :_destroy

app/views/shopping_lists/edit.html.haml
= render "shared/errors", obj: @shopping_list

= render "form"

.mx-5.my-2= link_to "<<< Back", shopping_lists_path, class: "text-dark text-decoration-none"

app/views/shopping_lists/index.html.haml
.d-grid.gap-2.d-md-block.mx-5
  %button.btn.btn-dark.me-2.position-relative(type="button")= link_to "New Shopping List", new_shopping_list_path, class: "text-light text-decoration-none stretched-link"

#shopping-lists-container.d-flex.flex-column.align-items-stretch.my-2.mx-5.bg-light
  - @shopping_lists.group_by(&:status).sort.reverse.each do |status, shopping_lists|
    %h4.m-2= status
    .m-2
      - shopping_lists.each do |shopping_list|
        .d-flex.align-items-center.list-group-item.list-group-item-action.p-1
          .px-2.shc-icon{:class => shopping_list.pending? ? "pending-icon" : "done-icon"}
          .px-2.text-muted.fw-light= shopping_list.shopping_day
          .px-2.flex-grow-1= link_to shopping_list.name, shopping_list, class: "text-align-center text-dark text-decoration-none"
          .px-2.mx-2.shc-icon.action-icon.position-relative{:class => shopping_list.shopping_list_email ? "email-set-icon" : "email-not-set-icon"}= link_to "", edit_shopping_list_path(shopping_list), class: "stretched-link"
          .px-2.mx-2.edit-icon.shc-icon.action-icon.position-relative= link_to "", edit_shopping_list_path(shopping_list), class: "stretched-link"
          .px-2.mx-2.delete-icon.shc-icon.action-icon.position-relative= link_to "", shopping_list, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "stretched-link"

.mx-5.my-2= link_to "<<< Back", root_path, class: "text-dark text-decoration-none"

app/views/shopping_lists/new.html.haml
= render "shared/errors", obj: @shopping_list

= render "form"

.mx-5.my-2= link_to "<<< Back", shopping_lists_path, class: "text-dark text-decoration-none"

app/views/shopping_lists/show.csv.haml
= CSV.generate_line([@shopping_list.shopping_day, @shopping_list.name])
- headers = ["Product", "Quantity", "Unit"]
= CSV.generate_line headers
- @shopping_list.shopping_list_products.each do |shlp|
  = CSV.generate_line([shlp.product.name, shlp.quantity])

app/views/shopping_lists/show.html.haml
.bg-light.mx-5
  .d-flex.p-1
    .px-2.shc-icon{:class => @shopping_list.status=="pending" ? "pending-icon" : "done-icon"}
    .px-2= @shopping_list.shopping_day
    .px-2.flex-grow-1.text-center= @shopping_list.name
    .px-2.mx-2.edit-icon.action-icon.shc-icon.position-relative= link_to "", edit_shopping_list_path(@shopping_list), class: "stretched-link"
    .px-2.mx-2.delete-icon.action-icon.shc-icon.position-relative= link_to "", @shopping_list, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "stretched-link"
  %h4.my-3.text-center Products to buy:
  .row.mx-2
    .col-12.col-sm-8.mb-2
      - @shopping_list.shopping_list_products.each do |shl_product|
        .d-flex.align-items-center.list-group-item.list-group-item-action.p-1
          .px-2.flex-grow-1= shl_product.product.name
          .px-2= shl_product.quantity
    .col
      %button.btn.btn-dark.m-2.position-relative(type="button")= link_to "Export ExcelSheet", shopping_list_path(format: "xlsx"), class: "text-light text-decoration-none stretched-link"
      %button.btn.btn-dark.m-2.position-relative(type="button")= link_to "Export CSV", shopping_list_path(format: "csv"), class: "text-light text-decoration-none stretched-link"
      %button.btn.btn-dark.m-2.position-relative(type="button")= link_to "Export PDF", shopping_list_path(format: "pdf"), class: "text-light text-decoration-none stretched-link"
  - if @shopping_list.shopping_list_email.present?
    .p-1.px-2.d-flex
      .px-2 Email set up →
      .px-2
        %div= "File format: #{@shopping_list.shopping_list_email.file_format}"
        %div= "To: #{@shopping_list.shopping_list_email.recipient}"
        %div= "When: #{@shopping_list.shopping_list_email.send_date.to_fs(:short)}"
      = form_with url: send_email_now_shopping_list_path(@shopping_list) do |f|
        .p-2= f.submit "Send now", class: "btn btn-dark"
.mx-5.my-2= link_to "<<< Back", shopping_lists_path, class: "text-dark text-decoration-none"