config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  resources :shopping_lists do
    post "send_email_now", on: :member
  end
  resources :products
  resources :shopping_list_emails, only: %i(new create edit update destroy)
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  PRODUCT_TYPES = %w(
    fruit
    vegetable
    nuts
    meat
    egg
    seafood
    dairy_products
    cereal_products
    spices extras
    fat
    drink
    other
  ).freeze

  has_many :recipe_products
  has_many :recipes, through: :recipe_products
  has_one :product_calories

  has_many :shopping_list_products, dependent: :destroy
  has_many :shopping_lists, through: :shopping_list_products

  has_many :shopping_list_products, dependent: :destroy
  has_many :shopping_lists, through: :shopping_list_products

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }

  enum :product_type, { fruit: 0,
                        vegetable: 1,
                        nuts: 2,
                        meat: 3,
                        egg: 4,
                        seafood: 5,
                        dairy_products: 6,
                        cereal_products: 7,
                        spices: 8,
                        extras: 9,
                        fat: 10,
                        drink: 11,
                        other: 12 }
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProductsController < BaseApiController
      def index
        products = Product.all
        render json: products
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :product_types, only: %i(new edit create update)

  def index
    @grouped_products = repository.all_grouped_by_type
  end

  def show
    @product = repository.find(id: params[:id])
  end

  def new
    @product = repository.new_entity
  end

  def edit
    @product = repository.find(id: params[:id])
  end

  def create
    @product = repository.new_entity(attrs: product_params)
    @product = Products::UseCases::CreateProduct.new(@product).call
    if @product.errors.any?
      render :new, status: :unprocessable_entity, alert: @product.errors.messages
    else
      redirect_to product_url(@product), notice: "Product was successfully created."
    end
  end

  def update
    @product = repository.find(id: params[:id])
    @product = Products::UseCases::UpdateProduct.new(@product, product_params).call
    if @product.errors.any?
      render :edit, status: :unprocessable_entity, alert: @product.errors.messages
    else
      redirect_to product_url(@product), notice: "Product was successfully updated."
    end
  end

  def destroy
    Products::UseCases::DeleteProduct.new(params[:id]).call
    redirect_to products_url, status: :see_other, notice: "Product was successfully destroyed."
  end

  private

  def repository
    @repository ||= Products::Repository.new
  end

  def product_params
    params.require(:product).permit(:name, :product_type)
  end

  def product_types
    @product_types ||= repository.all.product_types.keys
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.haml
#form-container.bg-light.mx-5
  = form_for @product do |f|
    .row.m-2.py-4
      .col-12.col-sm-8
        #inputProductName= f.text_field :name, class: "form-control", placeholder: :name, disabled: @product.id.present?
      .col-12.col-sm-4
        #inputProductType= f.select :product_type, options_for_select(@product_types, f.object.product_type), {}, class: "form-select"
    .ps-4.pb-4
      = f.submit @product.id ? "Save" : "Create", class: "btn btn-dark me-2", type: "submit"
      = link_to "Show", @product, class: "btn btn-outline-dark" if @product.id

app/views/products/edit.html.haml
= render "shared/errors", obj: @product

= render "form"

.mx-5.my-2= link_to "<<< Back", products_path, class: "text-dark text-decoration-none"

app/views/products/index.html.haml
.d-grid.gap-2.d-md-block.mx-5
  %button.btn.btn-dark.me-2.position-relative(type="button")= link_to "New Product", new_product_path, class: "text-light text-decoration-none stretched-link"

#products-list-container.d-flex.my-2.mx-5.bg-light.position-relative
  %nav#products-list-navigation.d-flex.flex-column.align-items-start.p-2
    - @grouped_products.each do |type, products|
      %a.list-group-item.list-group-item-action.p-1{:href => "#product_type_#{type}"}= type&.titleize

  #products-list.scrollspy.flex-grow-1.p-3(data-bs-offset="0" data-bs-spy="scroll" data-bs-target="#products-list-navigation" tabindex="0")
    - @grouped_products.each do |type, products|
      %h4.mt-2{:id => "product_type_#{type}"}= type&.titleize
      - products.each do |product|
        .d-flex.align-items-center.list-group-item.list-group-item-action.p-1
          .px-2.flex-grow-1= link_to product.name, product, class: "text-dark text-decoration-none"
          .px-2.text-align-start.text-muted.fw-light= "(#{product&.product_calories&.calories} kcal in #{product&.product_calories&.grams}g)" if product.product_calories.present?
          .px-2.mx-2.edit-icon.action-icon.shc-icon.position-relative= link_to "", edit_product_path(product), class: "stretched-link"
          .px-2.mx-2.delete-icon.action-icon.shc-icon.position-relative= link_to "", product, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "stretched-link"

.mx-5.my-2= link_to "<<< Back", root_path, class: "text-dark text-decoration-none"

app/views/products/new.html.haml
= render "shared/errors", obj: @product

= render "form"

.mx-5.my-2= link_to "<<< Back", products_path, class: "text-dark text-decoration-none"

app/views/products/show.html.haml
.bg-light.mx-5
  .d-flex.p-1
    .px-2.text-muted.fw-light= "[ #{@product.product_type} ]"
    .px-2.flex-grow-1= @product.name
    .px-2.text-align-start.text-muted.fw-light= "(#{@product&.product_calories&.calories} kcal in 1 #{@product&.product_calories&.unit} / #{@product.product_calories&.grams}g)" if @product.product_calories.present?
    .px-2.mx-2.edit-icon.action-icon.shc-icon.position-relative= link_to "", edit_product_path(@product), class: "stretched-link"
    .px-2.mx-2.delete-icon.action-icon.shc-icon.position-relative= link_to "", @product, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "stretched-link"
  %h4.my-3.text-center= "Recipes with " + @product.name
  .my-2.mx-5.bg-light.position-relative
    .d-flex.flex-column.p-2
      - @product.recipes.each do |recipe|
        .d-flex.align-items-center.list-group-item.p-1
          .px-2.mx-2 mini IMG
          .px-2.flex-grow-1= link_to recipe.name, recipe, class: "text-dark text-decoration-none"
          .px-2.mx-2.edit-icon.action-icon.shc-icon.position-relative= link_to "", edit_recipe_path(recipe), class: "stretched-link"
          .px-2.mx-2.delete-icon.action-icon.shc-icon.position-relative= link_to "", recipe, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "stretched-link"

.mx-5.my-2= link_to "<<< Back", products_path, class: "text-dark text-decoration-none"